[database]
host     = "localhost"
name     = DB_NAME
user     = DB_USER
password = DB_PASSWORD

[redis]
host     = "localhost"
password = REDIS_PASSWORD

[web]
host  = "localhost"
port  = 7000

[api]
host  = "localhost"
port  = 7100
url   = "/api"

[tile]
host   = "localhost"
port   = 7200
url    = "/tile"
extent = "-19942765.3260505,-1637243.58853688,20012847.7359938,11528300.5677573"

[webpack]
host       = "localhost"
port       = 7999
publicPath = "/public/dist/"

[debug]
#showRoutes = true

[cdn]
#cache  = "/cdn"
[[cdn.libs]]
url     = "https://ajax.googleapis.com/ajax/libs"
scripts = [
  "jquery/1.11.3/jquery.min.js"
]
[[cdn.libs]]
url     = "https://cdnjs.cloudflare.com/ajax/libs"
styles  = [
  "twitter-bootstrap/3.3.5/css/bootstrap.min.css",
  "bootswatch/3.3.5/united/bootstrap.min.css",
  "font-awesome/4.4.0/css/font-awesome.min.css",
  "leaflet/0.7.5/leaflet.css"
]
scripts = [
  "twitter-bootstrap/3.3.5/js/bootstrap.min.js",
  "leaflet/0.7.5/leaflet.js",
  "highcharts/4.1.8/highcharts.js",
  "highcharts/4.1.8/modules/exporting.js"
]
