[database]
host     = "localhost"
name     = DB_NAME
user     = DB_USER
password = DB_PASSWORD

[redis]
host     = "localhost"
password = REDIS_PASSWORD

[server]
host = "0.0.0.0"
port = 7000

[webpack]
host       = "0.0.0.0"
port       = 7400
publicPath = "/public/dist/"

[tile]
host   = "0.0.0.0"
port   = 7800
extent = "-19942765.3260505,-1637243.58853688,20012847.7359938,11528300.5677573"
