[database]
host     = "localhost"
name     = DB_NAME
user     = DB_USER
password = DB_PASSWORD

[redis]
host     = "localhost"
password = REDIS_PASSWORD

[web]
host  = "localhost"
port  = 7000

[api]
host  = "localhost"
port  = 7100
url   = "/api"

[tile]
host   = "localhost"
port   = 7200
url    = "/tile"
extent = "-19942765.3260505,-1637243.58853688,20012847.7359938,11528300.5677573"

[webpack]
host       = "localhost"
port       = 7999
publicPath = "/public/dist/"

[debug]
#showRoutes = true

[vendors]
styles  = [
  "twitter-bootstrap/4.0.0-alpha/css/bootstrap.min.css",
  "font-awesome/4.4.0/css/font-awesome.min.css",
  "leaflet/1.0.0-beta.1/leaflet.css"
]
scripts = [
  "jquery/3.0.0-alpha1/jquery.min.js",
  "twitter-bootstrap/4.0.0-alpha/js/bootstrap.min.js",
  "leaflet/1.0.0-beta.1/leaflet.js",
  "highcharts/4.1.8/highcharts.js",
  "highcharts/4.1.8/modules/exporting.js"
]
